### PR TITLE
Add matching FutureOr extensions

### PR DESCRIPTION
**Pull request by kmcgill88**
Closes Issues https://github.com/shinayser/mocktailx/issues/2

### CODE REVIEW

**Comment by kmcgill88** [comment]
Did you want me to bump the package version or will you handle that?

**Comment by shinayser** [comment]
@kmcgill88 Yeah please! Then I will simply upload a new version to pub. Thanks for the pr man =)

**Comment by kmcgill88** [comment]
@shinayser I bumped just as a patch b/c this isn't a new API per say.

**Comment by shinayser** [comment]
Its online, v0.0.4 =)

**Pull request merged**
